"""initial schema

Revision ID: 59f870a53be2
Revises: 
Create Date: 2026-05-19 01:31:33.040287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '59f870a53be2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('auctions',
    sa.Column('auction_id', sa.String(), nullable=False),
    sa.Column('weapon', sa.String(), nullable=False),
    sa.Column('buyout_price', sa.Integer(), nullable=True),
    sa.Column('re_rolls', sa.Integer(), nullable=True),
    sa.Column('positive_stats', sa.String(), nullable=False),
    sa.Column('stat_values', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('negative_stat', sa.String(), nullable=True),
    sa.Column('first_seen_ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('disappeared', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('auction_id')
    )
    op.create_index(op.f('ix_auctions_weapon'), 'auctions', ['weapon'], unique=False)
    op.create_table('saved_grolls',
    sa.Column('auction_id', sa.String(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('saved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('auction_id')
    )
    op.create_table('weapon_price_samples',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('weapon', sa.String(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('price1', sa.Integer(), nullable=False),
    sa.Column('price2', sa.Integer(), nullable=False),
    sa.Column('price3', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weapon_price_samples_ts'), 'weapon_price_samples', ['ts'], unique=False)
    op.create_index(op.f('ix_weapon_price_samples_weapon'), 'weapon_price_samples', ['weapon'], unique=False)
    op.create_index('ix_weapon_price_samples_weapon_ts', 'weapon_price_samples', ['weapon', 'ts'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_weapon_price_samples_weapon_ts', table_name='weapon_price_samples')
    op.drop_index(op.f('ix_weapon_price_samples_weapon'), table_name='weapon_price_samples')
    op.drop_index(op.f('ix_weapon_price_samples_ts'), table_name='weapon_price_samples')
    op.drop_table('weapon_price_samples')
    op.drop_table('saved_grolls')
    op.drop_index(op.f('ix_auctions_weapon'), table_name='auctions')
    op.drop_table('auctions')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
